//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VELILER
    {
        public TBL_VELILER()
        {
            this.TBL_OGRENCILER = new HashSet<TBL_OGRENCILER>();
        }
    
        public int VELIID { get; set; }
        public string VELIANNE { get; set; }
        public string VELIBABA { get; set; }
        public string VELITEL1 { get; set; }
        public string VELITEL2 { get; set; }
        public string VELIMAIL { get; set; }
    
        public virtual ICollection<TBL_OGRENCILER> TBL_OGRENCILER { get; set; }
    }
}
